//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitorEnhance.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonitorEnhance.Lang.en_US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Close  的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flash radar 的本地化字符串。
        /// </summary>
        internal static string FlashRadar {
            get {
                return ResourceManager.GetString("FlashRadar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LeftAlt 的本地化字符串。
        /// </summary>
        internal static string LeftAlt {
            get {
                return ResourceManager.GetString("LeftAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LMB 的本地化字符串。
        /// </summary>
        internal static string LeftButton {
            get {
                return ResourceManager.GetString("LeftButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LeftShift 的本地化字符串。
        /// </summary>
        internal static string LeftShift {
            get {
                return ResourceManager.GetString("LeftShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open  的本地化字符串。
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ping radar 的本地化字符串。
        /// </summary>
        internal static string PingRadar {
            get {
                return ResourceManager.GetString("PingRadar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RMB 的本地化字符串。
        /// </summary>
        internal static string RightButton {
            get {
                return ResourceManager.GetString("RightButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select current target 的本地化字符串。
        /// </summary>
        internal static string SelectTarget {
            get {
                return ResourceManager.GetString("SelectTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShipDoor 的本地化字符串。
        /// </summary>
        internal static string ShipDoor {
            get {
                return ResourceManager.GetString("ShipDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch to player 的本地化字符串。
        /// </summary>
        internal static string SwitchPlayer {
            get {
                return ResourceManager.GetString("SwitchPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch to radar 的本地化字符串。
        /// </summary>
        internal static string SwitchRadar {
            get {
                return ResourceManager.GetString("SwitchRadar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Teleport player 的本地化字符串。
        /// </summary>
        internal static string TPPlayer {
            get {
                return ResourceManager.GetString("TPPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close clicked trap 的本地化字符串。
        /// </summary>
        internal static string TriggerTrap {
            get {
                return ResourceManager.GetString("TriggerTrap", resourceCulture);
            }
        }
    }
}
