//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitorEnhance.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly typed resource class for finding localized strings, etc.
    /// </summary>
    // This class is automatically generated by the StronglyTypedResourceBuilder
    // class automatically generated by tools like ResGen or Visual Studio.
    // To add or remove members, edit the .ResX file and then re-run ResGen
    // (with /str as a command option), or regenerate the VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ko_KR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ko_KR() {
        }
        
        /// <summary>
        /// Returns the ResourceManager instance of the cache used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonitorEnhance.Lang.ko_KR", typeof(ko_KR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        /// Rewrites the CurrentUICulture property of the current thread to perform an override of the
        /// All resource lookups that use this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Finds a localized string like Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        /// Finds localized strings like Flash radar.
        /// </summary>
        internal static string FlashRadar {
            get {
                return ResourceManager.GetString("FlashRadar", resourceCulture);
            }
        }
        
        /// <summary>
        /// Finds localized strings like LeftAlt.
        /// </summary>
        internal static string LeftAlt {
            get {
                return ResourceManager.GetString("LeftAlt", resourceCulture);
            }
        }
        
        /// <summary>
        /// Finds LMB-like localized strings.
        /// </summary>
        internal static string LeftButton {
            get {
                return ResourceManager.GetString("LeftButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Finds localized strings like LeftShift.
        /// </summary>
        internal static string LeftShift {
            get {
                return ResourceManager.GetString("LeftShift", resourceCulture);
            }
        }
        
        /// <summary>
        /// Finds localized strings like Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        /// Finds localized strings like Ping radar.
        /// </summary>
        internal static string PingRadar {
            get {
                return ResourceManager.GetString("PingRadar", resourceCulture);
            }
        }
        
        /// <summary>
        /// Finds a localized string like RMB.
        /// </summary>
        internal static string RightButton {
            get {
                return ResourceManager.GetString("RightButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Finds a localized string like Select current target.
        /// </summary>
        internal static string SelectTarget {
            get {
                return ResourceManager.GetString("SelectTarget", resourceCulture);
            }
        }
        
        /// <summary>
        /// Finds localized strings like ShipDoor.
        /// </summary>
        internal static string ShipDoor {
            get {
                return ResourceManager.GetString("ShipDoor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Finds localized strings like Switch to player.
        /// </summary>
        internal static string SwitchPlayer {
            get {
                return ResourceManager.GetString("SwitchPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        /// Finds localized strings like Switch to radar.
        /// </summary>
        internal static string SwitchRadar {
            get {
                return ResourceManager.GetString("SwitchRadar", resourceCulture);
            }
        }
        
        /// <summary>
        /// Finds localized strings like Teleport player.
        /// </summary>
        internal static string TPPlayer {
            get {
                return ResourceManager.GetString("TPPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        /// Finds localized strings like the Close clicked trap.
        /// </summary>
        internal static string TriggerTrap {
            get {
                return ResourceManager.GetString("TriggerTrap", resourceCulture);
            }
        }
    }
}
